### ISSUE TITLE
Latest version causing an error

### ISSUE THREAD

**Issue by jescalan** [jonathantneal/postcss-input-range#4]
I just upgraded to the latest version, running postcss through webpack, and it's throwing a loader error for me now, without a specific message. However, once I downgrade to `2.0.0`, it compiles correctly, so I assume it must be this package.

Looked through the commit, and I don't entirely understand why it would be breaking, but it is 😢

**Comment by Bootjack** [comment]
@jescalan Did you look at pull request #3? That addresses an error thrown during a webpack build, which should be logged as something like `Module build failed: TypeError: selector.walkPseudos is not a function`.

Not sure how much more detail you can get on your error, but it would be good to know if you're having the same issue.

**Comment by jescalan** [comment]
Yeah, I got module build failed but that was all it told me, strangely. I'll give it another shot when that PR gets merged, thanks for the look!

**Comment by caseprince** [comment]
Also seeing this error running with `"postcss-cli": "^2.6.0",` - downgraded to `2.0.0` for now.
